name: Download File

on:
  workflow_dispatch:
    inputs:
      file_url:
        description: 'Direct file URL to download'
        required: true
        default: 'https://s2.pesk.top/eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE3NjcyMjIwMDAsInN1YiI6IkR0U2VhcmNoIERlc2t0b3AgMjAyNC4wMiBCdWlsZCA4ODIxIFtQZXNrVG9wLmNvbV0ucmFyIiwic291cmNlIjoiaHR0cHM6XC9cL3Blc2t0b3AuY29tXC8ifQ.2hrZlHoBGZHrbqsOdzY8JbiZxM_Dy6cAcCPV8mzmlDI'

jobs:
  download-file:
    runs-on: ubuntu-latest
    steps:
      - name: Download file
        run: curl -L "${{ github.event.inputs.file_url }}" -o downloaded_file

      - name: Upload file as artifact
        uses: actions/upload-artifact@v4
        with:
          name: downloaded-file
          path: downloaded_file
